// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckGitAvailable():Promise<main.WorkspaceGitCheckResult>;

export function ClearHistory():Promise<void>;

export function CreateWorkspace(arg1:main.WorkspaceCreateRequest):Promise<main.WorkspaceManagerStore>;

export function DeleteHistoryDay(arg1:string):Promise<void>;

export function DeleteHistoryItem(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:main.WorkspaceDeleteRequest):Promise<main.WorkspaceDeleteResult>;

export function DetectWorkspaceGit(arg1:string):Promise<main.WorkspaceGitDetectionResult>;

export function DiscoverMCPServer(arg1:string):Promise<main.MCPDiscoverResult>;

export function EnsureWorkspaceGitRepo(arg1:string):Promise<main.WorkspaceGitActionResult>;

export function ExecuteHTTP(arg1:main.HttpRequest):Promise<main.HttpResponse>;

export function ExecuteMCPTool(arg1:main.MCPCallRequest):Promise<main.MCPCallResult>;

export function GetMCPPrompt(arg1:main.MCPPromptRequest):Promise<main.MCPPromptResultView>;

export function ImportMCPServers(arg1:string):Promise<main.MCPServerImportResult>;

export function ListWorkspaceManager():Promise<main.WorkspaceManagerStore>;

export function LoadBootstrapData():Promise<main.BootstrapData>;

export function LoadHistoryItem(arg1:string,arg2:string):Promise<main.HistoryItem>;

export function PreviewWorkspacePush(arg1:string):Promise<main.WorkspacePushPreview>;

export function PullWorkspace(arg1:string):Promise<main.WorkspaceGitActionResult>;

export function PushWorkspaceChanges(arg1:main.WorkspacePushRequest):Promise<main.WorkspaceGitActionResult>;

export function ReadMCPResource(arg1:string,arg2:string):Promise<main.MCPReadResourceResult>;

export function SaveCollections(arg1:main.CollectionStore):Promise<void>;

export function SaveHTTPHistory(arg1:main.HistoryStore):Promise<void>;

export function SaveMCPHistory(arg1:main.HistoryStore):Promise<void>;

export function SaveMCPServers(arg1:main.MCPServerStore):Promise<void>;

export function SaveSettings(arg1:main.SettingsStore):Promise<void>;

export function SaveWorkspace(arg1:main.WorkspaceStore):Promise<void>;

export function SelectFolder():Promise<string>;

export function SwitchWorkspace(arg1:string):Promise<main.BootstrapData>;

export function TestMCPServer(arg1:string):Promise<main.MCPServerTestResult>;

export function UpdateWorkspace(arg1:main.WorkspaceUpdateRequest):Promise<main.WorkspaceManagerStore>;

export function UpdateWorkspaceFeatureSettings(arg1:main.WorkspaceFeatureSettingsRequest):Promise<main.WorkspaceManagerStore>;
