// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryDay(arg1) {
  return window['go']['main']['App']['DeleteHistoryDay'](arg1);
}

export function DeleteHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteHistoryItem'](arg1);
}

export function DiscoverMCPServer(arg1) {
  return window['go']['main']['App']['DiscoverMCPServer'](arg1);
}

export function ExecuteHTTP(arg1) {
  return window['go']['main']['App']['ExecuteHTTP'](arg1);
}

export function ExecuteMCPTool(arg1) {
  return window['go']['main']['App']['ExecuteMCPTool'](arg1);
}

export function GetMCPPrompt(arg1) {
  return window['go']['main']['App']['GetMCPPrompt'](arg1);
}

export function ImportMCPServers(arg1) {
  return window['go']['main']['App']['ImportMCPServers'](arg1);
}

export function LoadBootstrapData() {
  return window['go']['main']['App']['LoadBootstrapData']();
}

export function LoadHistoryItem(arg1, arg2) {
  return window['go']['main']['App']['LoadHistoryItem'](arg1, arg2);
}

export function ReadMCPResource(arg1, arg2) {
  return window['go']['main']['App']['ReadMCPResource'](arg1, arg2);
}

export function SaveCollections(arg1) {
  return window['go']['main']['App']['SaveCollections'](arg1);
}

export function SaveHTTPHistory(arg1) {
  return window['go']['main']['App']['SaveHTTPHistory'](arg1);
}

export function SaveMCPHistory(arg1) {
  return window['go']['main']['App']['SaveMCPHistory'](arg1);
}

export function SaveMCPServers(arg1) {
  return window['go']['main']['App']['SaveMCPServers'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function TestMCPServer(arg1) {
  return window['go']['main']['App']['TestMCPServer'](arg1);
}
